"""add_cryptographic_signature_columns

Revision ID: 381773b44012
Revises: 464dcd1916ba
Create Date: 2026-07-20 21:08:24.496335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381773b44012'
down_revision: Union[str, None] = '464dcd1916ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_decisions', sa.Column('signature', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('signature', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'signature')
    op.drop_column('ai_decisions', 'signature')
    # ### end Alembic commands ###
