"""remove_blockchain_dependencies

Revision ID: 464dcd1916ba
Revises: None
Create Date: 2026-07-19 22:37:22.267835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464dcd1916ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bc_tx_actor'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_bc_tx_event_type_time'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_bc_tx_org'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_event_id'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_event_type'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_transaction_hash'), table_name='blockchain_transactions')
    op.drop_table('blockchain_transactions')
    op.drop_index(op.f('ix_ai_decisions_bc_verified'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_blockchain_tx_hash'), table_name='ai_decisions')
    op.drop_column('ai_decisions', 'digital_signature')
    op.drop_column('ai_decisions', 'blockchain_verified')
    op.drop_column('ai_decisions', 'blockchain_tx_hash')
    op.drop_index(op.f('ix_audit_logs_blockchain_tx_hash'), table_name='audit_logs')
    op.drop_column('audit_logs', 'event_hash')
    op.drop_column('audit_logs', 'blockchain_verified')
    op.drop_column('audit_logs', 'blockchain_tx_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('blockchain_tx_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('blockchain_verified', sa.BOOLEAN(), nullable=False))
    op.add_column('audit_logs', sa.Column('event_hash', sa.VARCHAR(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_blockchain_tx_hash'), 'audit_logs', ['blockchain_tx_hash'], unique=False)
    op.add_column('ai_decisions', sa.Column('blockchain_tx_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('ai_decisions', sa.Column('blockchain_verified', sa.BOOLEAN(), nullable=False))
    op.add_column('ai_decisions', sa.Column('digital_signature', sa.VARCHAR(length=512), nullable=True))
    op.create_index(op.f('ix_ai_decisions_blockchain_tx_hash'), 'ai_decisions', ['blockchain_tx_hash'], unique=False)
    op.create_index(op.f('ix_ai_decisions_bc_verified'), 'ai_decisions', ['blockchain_verified'], unique=False)
    op.create_table('blockchain_transactions',
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('block_number', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('payload_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('digital_signature', sa.VARCHAR(length=512), nullable=False),
    sa.Column('public_key', sa.VARCHAR(length=512), nullable=False),
    sa.Column('previous_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('merkle_root', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nonce', sa.VARCHAR(length=64), nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('organization_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gas_used', sa.FLOAT(), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=False),
    sa.Column('chain_id', sa.INTEGER(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_transactions_transaction_hash'), 'blockchain_transactions', ['transaction_hash'], unique=1)
    op.create_index(op.f('ix_blockchain_transactions_event_type'), 'blockchain_transactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_event_id'), 'blockchain_transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_bc_tx_org'), 'blockchain_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bc_tx_event_type_time'), 'blockchain_transactions', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_bc_tx_actor'), 'blockchain_transactions', ['actor_id'], unique=False)
    # ### end Alembic commands ###
